@host=http://localhost:5282

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "johndoe",
    "lastName": "smith",
    "email": "johndoe@example.com",
    "password": "password123"
}